FROM oven/bun:1

RUN apt-get update -y && apt-get install -y openssl

WORKDIR /usr/src/app



COPY . .

RUN bun install
RUN cd packages/db/prisma/schema.prisma && bunx prisma generate

EXPOSE 8080

CMD ["bun","run","start:backend"]
