FROM oven/bun:1

# RUN apt-get update -y && apt-get install -y openssl

WORKDIR /usr/src/app



COPY . .

RUN bun install
RUN cd packages/db && bunx prisma generate

EXPOSE 8080

CMD ["bun","run","start:backend"]
