name: deploy backend
on:
    push:
        branches: [main]
    
jobs:
    build:
        runs-on: ubuntu-latest
        steps:

            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Docker login
              uses: docker/login-action@v2
              with:
                username: ${{secrets.DOCKERHUB_USERNAME}}    
                password: ${{secrets.DOCKERHUB_PASSWORD}}    

            - name: build and push image
              uses: docker/build-push-action@v4
              with:
                context: .
                file: ./docker/Dockerfile.backend
                push: true
                tags: spi9325/mono-docker-cicd:${{ github.sha }}     
                